apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-csi-retain
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Premium_ZRS